---

name: Functional Tests for Log-Flagger

on:
  push:
    branches: [latest]
    paths:
      - 'apps/log_flagger/**.go'
      - '.github/workflows/app_flagger_functional_test.yml'
      - 'scripts/functional_test_flagger.sh'
  pull_request:
    branches: [latest]
    paths:
      - 'apps/log_flagger/**.go'
      - '.github/workflows/app_flagger_functional_test.yml'
      - 'scripts/functional_test_flagger.sh'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'apps/log_flagger/go.mod'

      - name: Building Go Binary
        run: bash scripts/build_apps.sh
        env:
          MODE_TEST: '1'

      - name: Functional Tests
        run: |
          FILE_LOG='/tmp/oxl-open-bot-list.log'
          bash scripts/functional_test_flagger.sh | tee -a "$FILE_LOG"

          echo ''
          echo '### CHECKING FOR ERROR-LOGS ###'
          if grep -E 'ERROR|failed' < "$FILE_LOG"
          then
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-output
          path: '/tmp/oxl-open-bot-list-out.csv'
          retention-days: 14
