---

name: Unit Test Downloader

on:
  push:
    branches: [latest]
    paths:
      - '**.go'
      - '.github/workflows/apps_unit_test.yml'
      - 'scripts/unit_tests.sh'
  pull_request:
    branches: [latest]
    paths:
      - '**.go'
      - '.github/workflows/apps_unit_test.yml'
      - 'scripts/unit_tests.sh'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'apps/downloader/go.mod'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'apps/log_flagger/go.mod'

      - name: Install dependencies
        run: |
          sudo apt install git
          go install gotest.tools/gotestsum@latest

      - name: Running Go Tests
        run: bash scripts/unit_tests.sh
