---

name: Lint CSV Configs

on:
  push:
    branches: [latest]
    paths:
      - '**.csv'
      - '.github/workflows/csv_lint.yml'
  pull_request:
    branches: [latest]
    paths:
      - '**.csv'
      - '.github/workflows/csv_lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'downloader/go.mod'

      - name: Install dependencies
        run: |
          sudo apt install git
          go install github.com/Clever/csvlint/cmd/csvlint@v0.3.0

      - name: Linting
        run: |
          FILE_ERROR='/tmp/oxl-open-bot-list-error.txt'
          for file in $(find . -type f -name "*.csv")
          do
            echo "> $file"
            go run github.com/Clever/csvlint/cmd/csvlint@v0.3.0 "$file" || touch "$FILE_ERROR"
          done

          if [ -f "$FILE_ERROR" ]
          then
            exit 1
          fi
